### ISSUE TITLE
Thread에서 크롤링 시 에러

### ISSUE THREAD

**Issue by hanbikan** [Hanbit-Kang/YouShouldCheckThis#1]
- [x] view 건드리는 코드 -> ui thread에서 실행시킬 것
 > MainActivity에서 InterfaceMainActivity interface를 ListViewAdapter의 public variable로 전달

- [x] Thread를 다수 생성 -> CPU에 부담되어 중도 중지? But, Items를 줄여도 일부 Thread가 끝까지 작동을 하지 않음
 > Android Studio - AVD Setting 수정

**Comment by Hanbit-Kang** [comment]
1. 해결 - MainActivity에서 InterfaceMainActivity interface를 ListViewAdapter의 public variable로 전달

**Comment by hanbikan** [comment]
- [x] " https://www.google.com/search?q=NAVER&tbm=fin "에서 검색 시 " https://www.google.com/finance/quote/035420:KRX "와 같은 주소로 Redirect 되어 오류 야기 ... 해결 방안: KRX의 종목코드를 저장하여 치환하여 새 주소로 url 설정
 > "google.com/search?q="에 "[StockName]%20주가" 키워드
