### ISSUE TITLE
어플리케이션이 강제 종료되는 버그가 있읍니다.

### ISSUE THREAD

**Issue by NewCenturyDev** [Hanbit-Kang/YouShouldCheckThis#3]
앱에 너무많은 종목을 추가하거나(스크롤이 발생될 정도)
없는 종목을 추가할 경우 어플리케이션이 강제 종료되는 버그가 발생합니다.
없는 종목을 여러개 추가하거나, 스크롤이 생길 정도로 많은 종목을 추가했을때도 정상 작동되는지 확인이 필요합니다.

하지만 Not in service 니까 봐줄께용~

**Comment by hanbikan** [comment]
후.. 성민쿤 고맙당 해결 완료!
문제 원인은 ListViewAdapter가 view를 리스트 내의 모든 아이템에 대해서 얻어오는 것이 아니라, 현재 보이는 것들에 한해서만 view를 가져오는 것이므로, 현재 보이지 않는 items의 view에 접근이 불가능해서 그랬음..
